name: main_workflow

on: 
  push:
    branches:
      - nodejs_linter_job
jobs:
    primerjob:
      name: linter-execution
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Linter execution
          uses: github/super-linter@v4
          env:
            DEFAULT_BRANCH: nodejs_example
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: /
            JAVASCRIPT_ES_CONFIG_FILE: eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true